<?php
/**
 * SuiteCRM Configuration Template
 * This file is automatically generated during Docker startup
 * @fileoverview Configuration template for SuiteCRM Docker environment
 */

if (!defined('sugarEntry') || !sugarEntry) {
    die('Not A Valid Entry Point');
}

$sugar_config = array(
    // Database Configuration
    'dbconfig' => array(
        'db_host_name' => '${DATABASE_HOST}',
        'db_host_instance' => 'SQLEXPRESS',
        'db_user_name' => '${DATABASE_USER}',
        'db_password' => '${DATABASE_PASSWORD}',
        'db_name' => '${DATABASE_NAME}',
        'db_type' => 'mysql',
        'db_port' => '${DATABASE_PORT}',
        'db_manager' => 'MysqliManager',
    ),

    // Site Configuration
    'site_url' => '${SITE_URL}',
    'host_name' => '${SITE_HOST}',
    'site_security_key' => '${SITE_SECURITY_KEY}',
    'unique_key' => '${UNIQUE_KEY}',

    // System Configuration
    'system_name' => '${SYSTEM_NAME}',
    'installer_locked' => true,
    'disable_persistent_connections' => '${DISABLE_PERSISTENT_CONNECTIONS}',
    'default_charset' => 'UTF-8',
    'default_email_charset' => 'UTF-8',
    'default_export_charset' => 'UTF-8',
    'default_language' => 'en_us',
    'default_locale_name_format' => 's f l',
    'disable_vardefs' => false,
    'display_email_template_variable_chooser' => false,
    'display_inbound_email_buttons' => false,
    'hide_subpanels' => false,
    'list_max_entries_per_page' => 20,
    'list_max_entries_per_subpanel' => 10,
    'history_max_viewed' => 50,
    'max_record_fetch_size' => 1000,

    // Logging Configuration
    'logger' => array(
        'level' => '${LOG_LEVEL}',
        'file' => array(
            'ext' => '.log',
            'name' => 'suitecrm',
            'dateFormat' => '%c',
            'maxSize' => '10MB',
            'maxLogs' => 10,
            'suffix' => '',
        ),
    ),
    'log_file' => 'suitecrm.log',
    'log_dir' => '.',

    // Cache Configuration
    'cache_dir' => 'cache/',
    'session_dir' => '',
    'tmp_dir' => 'cache/xml/',
    'upload_dir' => 'upload/',
    'upload_maxsize' => 30000000,
    'import_max_execution_time' => 3600,

    // Performance Configuration
    'disable_count_query' => false,
    'disable_vcr' => true,
    'save_query' => '${SAVE_QUERY}',
    'slow_query_time_msec' => '100',

    // Security Configuration
    'verify_client_ip' => true,
    'passwordsetting' => array(
        'SystemGeneratedPasswordON' => '',
        'generatepasswordtmpl' => '',
        'lostpasswordtmpl' => '',
        'forgotpasswordON' => true,
        'linkexpiration' => '1',
        'linkexpirationtime' => '30',
        'linkexpirationtype' => '1',
        'systexpiration' => '0',
        'systexpirationtime' => '',
        'systexpirationtype' => '0',
        'systexpirationlogin' => '',
    ),

    // Theme Configuration
    'default_theme' => 'SuiteP',
    'default_user_theme' => 'SuiteP',

    // Currency Configuration
    'default_currency_name' => 'US Dollars',
    'default_currency_symbol' => '$',
    'default_currency_iso4217' => 'USD',
    'default_currency_significant_digits' => 2,

    // Date/Time Configuration
    'default_date_format' => 'm/d/Y',
    'default_time_format' => 'H:i',
    'default_datetime_format' => 'm/d/Y H:i',
    'default_timezone' => '${TIMEZONE}',

    // Email Configuration
    'emailSettings' => array(
        'defaultOutboundFromName' => '${SYSTEM_NAME}',
        'defaultOutboundFromEmail' => 'admin@example.com',
    ),

    // Feature Configuration
    'enable_action_menu' => true,
    'enable_line_editing_detail' => true,
    'enable_line_editing_list' => true,
    'admin_export_only' => false,
    'export_delimiter' => ',',
    'default_number_grouping_seperator' => ',',
    'default_decimal_seperator' => '.',

    // Module Configuration
    'moduleInstaller' => array(
        'packageScan' => false,
    ),

    // OAuth2 Configuration (loaded from config_override.php)
    'oauth2_encryption_key' => '${OAUTH2_ENCRYPTION_KEY}',

    // Search Configuration
    'search' => array(
        'controller' => 'UnifiedSearch',
        'defaultEngine' => 'BasicSearchEngine',
    ),

    // Version Information
    'sugar_version' => '6.5.25',
    'suitecrm_version' => '8.0.0',

    // Additional settings
    'resource_management' => array(
        'special_query_limit' => 50000,
        'special_query_modules' => array(
            'Reports',
            'Export',
            'Import',
            'Administration',
            'Sync'
        ),
        'default_limit' => 1000,
    ),

    // Demo data flag
    'demoData' => '${DEMO_DATA}',
); 